Fixed minor typos and script errors
twiddlingbits/twr-wasm pull request #4
Opened 2024-07-28 20:02 UTC by JohnDog3112

* Re-fixed .sh scripts to use = when checking for the OS (using spaces in between this time)
* As mentioned in #3 :

2024-07-28 23:05 UTC, twiddlingbits requested changes
I don't think they way you changed this will work.  I believe the trick was the quotes around $(uname -o):

if [ "$(uname -o)" = "Msys" ]; then

that was what i tried to say in the email i sent -- that is what i learned from asking OpenAI.  The quote are important if there is an empty result, apparently.

2024-07-28 23:06 UTC, twiddlingbits approved these changes

2024-07-28 23:25 UTC, JohnDog3112 commented
> that was what i tried to say in the email i sent -- that is what i learned from asking OpenAI. The quote are important if there is an empty result, apparently.

On my system, the quotes didn't seem to make a difference, but I added them just in case it effects other peoples systems.

2024-07-29 01:53 UTC, twiddlingbits requested changes
This version still has the extra spacing that you say caused the issue?  Should you remove that extra two spaces around the -?

2024-07-29 12:15 UTC, merged